version: '3.3'

services:

  geth:
    image: ethereum/client-go:stable
    container_name: ${DOCKER_CONTAINER_PREFIX}_geth
    restart: always
    ports:
      - 8545:8545
      - 8546:8546
      - 8547:8547
      - 30303:30303
    env_file:
      - ./../.env
    volumes:
      - ./ethereum:/root/.ethereum
    command: --rpc --rpcport 8545 --rpcaddr 0.0.0.0 --rpcapi eth,web3 --rpcvhosts '*' --syncmode full

  nodejs:
    image: ${DOCKER_IMAGE_PREFIX}_nodejs:${DOCKER_TAG}
    container_name: ${DOCKER_CONTAINER_PREFIX}_nodejs
    build:
      context: ./../
      dockerfile: ./devops/nodejs/Dockerfile
    volumes:
      - ./..:/home/app
    env_file:
      - ./../.env
    ports:
      - ${PORT}:${PORT}
    command: npm run dev
    links:
      - geth
