version: '3.3'

services:

  nodejs:
    image: ${DOCKER_IMAGE_PREFIX}_nodejs:${DOCKER_TAG}
    container_name: ${DOCKER_CONTAINER_PREFIX}_nodejs
    build:
      context: ./../
      dockerfile: ./devops/nodejs/Dockerfile
    volumes:
      - ./..:/home/app
    env_file:
      - ./../.env
    ports:
      - ${PORT}:${PORT}
    command: npm run dev
